import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Home from "../../Components/Home/Home";


export const metadata = {
  title: "Personal Website",
  description: "Generated by create next app",
};
console.log("Home component import:", Home);
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className="grid grid-cols-3 gap-10">
          <div>
            <Home></Home>
          </div>
          <div className="col-span-2">
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
